#############################################################################
# Makefile for building: Maman14
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Mar 15 05:07:14 2018
# Project:  Maman14.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Maman14.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -ansi -Wall -pedantic
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Compile

assembler: firstIteration.o \
		main.o \
		helper.o \
		symbolTable.o \
		LinkedList.o \
		secondIteration.o \
		fileCreator.o \
		Parsing.o \
		commandsToBinary.o \
		errorPrinter.o
	$(CC) -g $(CFLAGS) $(INCPATH) -o assembler

main.o: main.c main.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

firstIteration.o: firstIteration.c firstIteration.h \
		main.h \
		helper.h \
		symbolTable.h \
		LinkedList.h \
		secondIteration.h \
		fileCreator.h \
		Parsing.h \
		commandsToBinary.h \
		errorPrinter.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o firstIteration.o firstIteration.c

secondIteration.o: secondIteration.c secondIteration.h \
		main.h \
		helper.h \
		symbolTable.h \
		LinkedList.h \
		fileCreator.h \
		Parsing.h \
		commandsToBinary.h \
		errorPrinter.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o secondIteration.o secondIteration.c

symbolTable.o: symbolTable.c symbolTable.h \
		main.h \
		LinkedList.h \
		helper.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o symbolTable.o symbolTable.c

helper.o: helper.c helper.h \
		main.h \
		symbolTable.h \
		LinkedList.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o helper.o helper.c

LinkedList.o: LinkedList.c LinkedList.h \
		main.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinkedList.o LinkedList.c

Parsing.o: Parsing.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o Parsing.o Parsing.c

fileCreator.o: fileCreator.c fileCreator.h \
		symbolTable.h \
		main.h \
		LinkedList.h \
		helper.h \
		Parsing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fileCreator.o fileCreator.c

commandsToBinary.o: commandsToBinary.c commandsToBinary.h \
		main.h \
		symbolTable.h \
		LinkedList.h \
		helper.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o commandsToBinary.o commandsToBinary.c

errorPrinter.o: errorPrinter.c errorPrinter.h \
		main.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o errorPrinter.o errorPrinter.c


